// SPDX-License-Identifier: MIT
// FILE: ZKNOX_NTT_falcon_fused.sol
// GENERATED by pythonref/gen_ntt_fused.py -- edit the generator, not this file.
//
// Fused radix-8 packed-SWAR NTT for Falcon-512 (q = 12289, n = 512). Same
// layout as ZKNOX_NTT_falcon_packed.sol (128 words of four 64-bit lanes,
// coefficient 4w+j in lane j of word w), same twiddle tables, same twiddle per
// butterfly. Only the SCHEDULE changes:
//
//   forward   A : t=256,128,64 fused  octet (i, i+16, ..., i+112), 16 octets,
//                 input read STRAIGHT from the 16-bit compact form (one
//                 multiply spreads a 64-bit chunk into four lanes)
//             B : t=32,16,8   fused  octet (16b+r, +2, ..., +14), 16 octets
//             C : t=4 on the word pair (2j, 2j+1), then t=2 and t=1 in-word on
//                 extracted scalars with native mulmod
//   inverse   C': pointwise product with the compact public key folded into
//                 the lane extraction (mulmod, exact), t=1 and t=2 in-word,
//                 t=4 on the pair; output lanes < 2q
//             B': t=8,16,32  fused, sums never reduced (lanes < 16q)
//             A': t=64,128,256 fused, n^-1 folded into the last layer, outputs
//                 CANONICAL (< q)
//
// Each octet is loaded once, run through three layers on the stack and stored
// once: 8 loads + 8 stores per 12 word-butterflies instead of 24 + 24, and one
// loop iteration per 12 butterflies instead of one per butterfly.
//
// Bounds (single-step Barrett, M40 = floor(2^40/q): residue < 2q, lane-local
// as long as x * M40 < 2^64, i.e. x < 2^37.6):
//   forward: lanes enter canonical and grow by 2q per layer (V < 2q, bias 2q),
//            so < 19q after nine layers; twiddle products < 19q*q < 2^28.
//   inverse: lanes < 2q after C', sums double per layer without reduction
//            (< 16q after B', < 128q before the folded last layer); the
//            difference branch (u + Kq - v) < 2Kq with K the entry bound, so
//            every product is < 128q*q < 2^31 and every Barrett multiply < 2^58.
// The saturated (all q-1) vectors in test/ntt_fused.t.sol exercise both.
pragma solidity ^0.8.25;

import "./ZKNOX_falcon_utils.sol";

uint256 constant _QHAT24 = 0x0000000000ffffff0000000000ffffff0000000000ffffff0000000000ffffff;
uint256 constant _L64 = 0xffffffffffffffff;
// in-word SWAR layers: lanes (0,1), lanes (0,2), lane 2, and 2q in those lanes
uint256 constant _LO2 = 0xffffffffffffffffffffffffffffffff;
uint256 constant _M02 = 0x0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff;
uint256 constant _L2 = 0x0000000000000000ffffffffffffffff00000000000000000000000000000000;
uint256 constant _Q2_01 = 0x0000000000000000000000000000000000000000000060020000000000006002;
uint256 constant _Q2_02 = 0x0000000000000000000000000000600200000000000000000000000000006002;
uint256 constant _Q4_1 = 0x0000000000003001000000000000300100000000000030010000000000003001;
uint256 constant _Q4_2 = 0x0000000000006002000000000000600200000000000060020000000000006002;
uint256 constant _Q4_4 = 0x000000000000c004000000000000c004000000000000c004000000000000c004;
uint256 constant _Q4_8 = 0x0000000000018008000000000001800800000000000180080000000000018008;
uint256 constant _Q4_16 = 0x0000000000030010000000000003001000000000000300100000000000030010;
uint256 constant _Q4_32 = 0x0000000000060020000000000006002000000000000600200000000000060020;
uint256 constant _Q4_64 = 0x00000000000c004000000000000c004000000000000c004000000000000c0040;
// canonicalisation of a lane x < 2q: x >= q  <=>  bit 14 of (x + 2^14 - q)
uint256 constant _C14 = 0x0000000000000fff0000000000000fff0000000000000fff0000000000000fff;
uint256 constant _H14 = 0x0000000000004000000000000000400000000000000040000000000000004000;
// 16-bit compact chunk -> 64-bit lanes: v * (1 + 2^48 + 2^96 + 2^144) lands
// field k at bit 64k; the other partial products never reach a lane's low 16
// bits when every field is < 2^15 (fields that are not are rejected by the
// range check, which reads the compact word directly)
uint256 constant _SPREAD = 0x0000000000000000000000000001000000000001000000000001000000000001;
uint256 constant _M16L = 0x000000000000ffff000000000000ffff000000000000ffff000000000000ffff;

// ---------------------------------------------------------------------------
// twiddle tables, identical to ZKNOX_NTT_falcon_packed.sol (16 x 16-bit per
// word, psirev[i] = field i & 15 of word i >> 4). Returned as a raw pointer so
// that passing them to the passes costs nothing.
// ---------------------------------------------------------------------------
function _fwTableFused() pure returns (uint256 tb) {
    uint256[32] memory psirev = [
        uint256(0x16e40c7b04bc29930e25261022510dd61fdb166802d22ae80fcb1be72a3a0001),
        0x5471c8f1970230116c4139f1e1216602549244324622dce2c4c25c00a4f1d2c,
        0x270b2bdb222012c50e8023c2254612ee2ad313de0bc623802ceb2c462b6f090f,
        0x2d2b1dfe28c42f752531299e1f622b68093e24161ce1246e2c191f212fb00c13,
        0x27d81c1d0cd40b410ca902d9232807dd06a00594014e097a19861218112404ec,
        0x18ea1ce720a525561a5b00910d830e351f7a260d2e9e0d36218629221bc62193,
        0x2624056522011fb01c841b2e10b629780220169f0153265d000903fe01e024e7,
        0x1b030b1500821eff095c116423210f6d1c360895007609ac1687033b215d2c48,
        0x2bec0b2b26501394164224a112fd01620ec22108030501862bd61c1401ba0961,
        0x2de0139b0e78258b1fd2126a00f206012a61214e2407001b1c2506601cec03f9,
        0x268b186a277625fb0bab17860e3e267c2c96213d29ba1c911f4513e0139303ea,
        0x77805622e4e1f10094d1abd200101ed0cb02b4a149d04901ddc2e6d085f2bd8,
        0x2910067f1dd32a6f0a9014ab134a0e3411552ffe0c4d2f611cca2f900f4b0876,
        0x5cc1ce22525144b0a550fd527001c4f1114087e1ec324e2233a0fd906990d24,
        0x2031273824bd2b800c72151f27b3065e0db614d40b3126bf2468207725832352,
        0x1dc0dcb13290f910608277f01a41a4a00f30bc8029f244923c11bba22b926a2,
        0x118d237f27f814f9150728ea015e05e818cb29d22a30263d05cb171b04ef0031,
        0x129207422e57230e0b6d015b2154284a02d300ae069d24400a5f199a1915254f,
        0x28f424bf27fe07a2267217fe02400f7b22380d6a00da0b5c28ce093910130bd6,
        0x50d1d801d5b15352e3c171401a20ebc14d5281216f408e9009c253220800f97,
        0x20302171048717662c4d2b872a850145249a214f0fed2051028c168617d30127,
        0x14b1181a0f7405502b511bc126061817063a28571c0f17490a842f5910ca0d01,
        0x2cbe1850220f1090052723b302c50fce081e045810e207a601b9039a2bdf2012,
        0x1b780efa18e21eb01a932413292e23ce263a247d169629e32fc10e4802ab099b,
        0x2800133005292f41228c12ac125a13c10313226703f21aa523ca1fb824991b88,
        0x27b2009724ea0f75171226382e52062b0c662fcd2533052b22f9185a190f02a5,
        0x10742c320d6e24e52bb0008e19d00d9518892c8c1c7007a42c160dcc2f102fc7,
        0x1df117bd0cbf21f117b40e1220112e5c2da408fe01f81f8c16fe12ae1a27242c,
        0x2be71e4915450f14258604a6211717e621342f6e1ab11161128d1a601d4c1e8e,
        0x2c0717252bf022471a3b07b526d92b0314c3201613341f1d2df70879234313d7,
        0x294101901808135421c61ada191b17f82fc90c7f14561a6807c306a60ded028e,
        0x2b1b03cd1ac62ab207820f27206328102e83013c206d01d417cd0e7e154614db
    ];
    assembly ("memory-safe") {
        tb := psirev
    }
}

function _invTableFused() pure returns (uint256 tb) {
    uint256[32] memory psirev = [
        uint256(0x222b0db009f121dc066e2b452386191d05192d2f19991026141a203605c70001),
        0x12d525b20a4103b502330b9f0bbe0ab819a111ef1c62193d0d00169113722aba,
        0x23ee005110e003e80b9313200beb26c30499109f06630ad0008c073d120302d6,
        0x26f2049203bb03160c81243b1c23052e1d130abb0c3f21811d3c0de1042608f6,
        0x3b90ea42cc6197a26552f8b276c13cb20940ce01e9d26a511022f7f24ec14fe,
        0xb1a2e212c032ff809a42eae19622de106891f4b14d3137d10510e002a9c09dd,
        0xe6e143b06df0e7b22cb016309f4108721cc227e2f7015a60aab0f5c131a1717,
        0x2b151edd1de9167b26872eb32a6d296128240cd92d28235824c0232d13e40829,
        0x95f0d4814470c400bb82d6224392f0e15b72e5d088229f920701cd822362e25,
        0xcaf0a7e0f8a0b99094224d01b2d224b29a3084e1ae2238f04810b4408c90fd0,
        0x22dd296820280cc70b1f113e27831eed13b20901202c25ac1bb60adc131f2a35,
        0x278b20b60071133700a023b400031eac21cd1cb71b5625710592122e298206f1,
        0x42927a2019412252b711b6404b723512e141000154426b410f101b32a9f2889,
        0x2c171c6e1c2110bc137006470ec4036b098521c3187b24560a06088b17970976,
        0x2c08131529a113dc2fe60bfa0eb305a02a002f0f1d97102f0a7621891c660221,
        0x26a02e4713ed042b2e7b2cfc0ef9213f2e9f1d040b6019bf1c6d09b124d60415,
        0x1b261abb218318342e2d0f942ec5017e07f10f9e20da287f054f153b2c3404e6,
        0x2d732214295b283e15991bab23820038180916e615270e3b1cad17f92e7106c0,
        0x1c2a0cbe2788020a10e41ccd0feb1b3e04fe0928284c15c60dba041118dc03fa,
        0x117312b515a11d741ea0155000930ecd181b0eea2b5b0a7b20ed1abc11b8041a,
        0xbd515da1d53190310752e092703025d01a50ff021ef184d0e10234218441210,
        0x3a00f1223503eb285d139103751778226c16312f7304510b1c229303cf1f8d,
        0x2d5c16f217a70d082ad60ace0034239b29d601af09c918ef208c0b172f6a084f,
        0x14790b6810490c37155c2c0f0d9a2cee1c401da71d550d7500c02ad81cd10801,
        0x26662d5621b90040061e196b0b8409c70c3306d30bee156e1151171f21071489,
        0xfef04222c672e48285b1f1f2ba927e320332d3c0c4e2ada1f710df217b10343,
        0x23001f3700a8257d18b813f207aa29c717ea09fb144004b02ab1208d17e71b50,
        0x2eda182e197b2d750fb020140eb20b672ebc057c047a03b4189b2b7a0e900fd1,
        0x206a0f810acf2f652718190d07ef1b2c21452e5f18ed01c51acc12a612812af4,
        0x242b1fee26c8073324a52f2722970dc920862dc11803098f285f08030b42070d,
        0xab216ec166725a20bc129642f532d2e07b70ead2ea624940cf301aa28bf1d6f,
        0x2fd02b1218e62a3609c405d1062f17362a192ea307171afa1b0808090c821e74
    ];
    assembly ("memory-safe") {
        tb := psirev
    }
}

/// @dev Forward pass A: t = 256, 128, 64 on the octet (i, i+16, ..., i+112),
///      read straight from the compact form (word i>>2, chunk i&3 of each
///      source word). Twiddles psirev[1..7] are literals.
function _fwPassA(uint256[] memory c) pure returns (uint256[] memory A) {
    A = new uint256[](128);
    assembly ("memory-safe") {
        for { let i := 0 } lt(i, 16) { i := add(i, 1) } {
            let p := add(add(A, 32), shl(5, i))
            {
                let src := add(add(c, 32), shl(5, shr(2, i)))
                let sh := shl(6, and(i, 3))
                for { let k := 0 } lt(k, 8) { k := add(k, 1) } {
                    mstore(add(p, shl(9, k)), and(mul(and(shr(sh, mload(add(src, shl(7, k)))), _L64), _SPREAD), _M16L))
                }
            }
            let c0, c2, c4, c6
            {
                let u0 := mload(p)
                let t := mul(mload(add(p, 0x800)), 0x2a3a)
                t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                let a0 := add(u0, t)
                u0 := sub(add(u0, _Q4_2), t)
                let u2 := mload(add(p, 0x400))
                t := mul(mload(add(p, 0xc00)), 0x2a3a)
                t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                let a2 := add(u2, t)
                u2 := sub(add(u2, _Q4_2), t)
                t := mul(a2, 0x1be7)
                t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                c0 := add(a0, t)
                c2 := sub(add(a0, _Q4_2), t)
                t := mul(u2, 0xfcb)
                t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                c4 := add(u0, t)
                c6 := sub(add(u0, _Q4_2), t)
            }
            {
                let u1 := mload(add(p, 0x200))
                let t := mul(mload(add(p, 0xa00)), 0x2a3a)
                t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                let a1 := add(u1, t)
                let b1 := sub(add(u1, _Q4_2), t)
                u1 := mload(add(p, 0x600))
                t := mul(mload(add(p, 0xe00)), 0x2a3a)
                t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                let a3 := add(u1, t)
                u1 := sub(add(u1, _Q4_2), t)
                t := mul(a3, 0x1be7)
                t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                a3 := sub(add(a1, _Q4_2), t)
                a1 := add(a1, t)
                t := mul(u1, 0xfcb)
                t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                u1 := sub(add(b1, _Q4_2), t)
                b1 := add(b1, t)
                t := mul(a1, 0x2ae8)
                t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                mstore(p, add(c0, t))
                mstore(add(p, 0x200), sub(add(c0, _Q4_2), t))
                t := mul(a3, 0x2d2)
                t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                mstore(add(p, 0x400), add(c2, t))
                mstore(add(p, 0x600), sub(add(c2, _Q4_2), t))
                t := mul(b1, 0x1668)
                t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                mstore(add(p, 0x800), add(c4, t))
                mstore(add(p, 0xa00), sub(add(c4, _Q4_2), t))
                t := mul(u1, 0x1fdb)
                t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                mstore(add(p, 0xc00), add(c6, t))
                mstore(add(p, 0xe00), sub(add(c6, _Q4_2), t))
            }
        }
    }
}

/// @dev Forward pass B: t = 32, 16, 8 on the octets (16b + r, +2, ..., +14).
///      The seven twiddles of block b are packed once into the scratch word at 0.
function _fwPassB(uint256[] memory A, uint256 tb) pure {
    assembly ("memory-safe") {
        for { let b := 0 } lt(b, 8) { b := add(b, 1) } {
            {
                let w := mload(add(tb, add(64, shl(5, shr(2, b)))))
                mstore(
                    0,
                    or(
                        or(
                            and(shr(shl(4, add(8, b)), mload(tb)), 0xffff),
                            shl(16, and(shr(shl(5, b), mload(add(tb, 32))), 0xffffffff))
                        ),
                        shl(48, and(shr(shl(6, and(b, 3)), w), _L64))
                    )
                )
            }
            let p := add(add(A, 32), shl(9, b))
            for { let r := 0 } lt(r, 2) { r := add(r, 1) } {
                let c0, c2, c4, c6
                {
                    let u0 := mload(p)
                    let t := mul(mload(add(p, 0x100)), and(mload(0), 0xffff))
                    t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                    let a0 := add(u0, t)
                    u0 := sub(add(u0, _Q4_2), t)
                    let u2 := mload(add(p, 0x80))
                    t := mul(mload(add(p, 0x180)), and(mload(0), 0xffff))
                    t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                    let a2 := add(u2, t)
                    u2 := sub(add(u2, _Q4_2), t)
                    t := mul(a2, and(shr(16, mload(0)), 0xffff))
                    t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                    c0 := add(a0, t)
                    c2 := sub(add(a0, _Q4_2), t)
                    t := mul(u2, and(shr(32, mload(0)), 0xffff))
                    t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                    c4 := add(u0, t)
                    c6 := sub(add(u0, _Q4_2), t)
                }
                {
                    let u1 := mload(add(p, 0x40))
                    let t := mul(mload(add(p, 0x140)), and(mload(0), 0xffff))
                    t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                    let a1 := add(u1, t)
                    let b1 := sub(add(u1, _Q4_2), t)
                    u1 := mload(add(p, 0xc0))
                    t := mul(mload(add(p, 0x1c0)), and(mload(0), 0xffff))
                    t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                    let a3 := add(u1, t)
                    u1 := sub(add(u1, _Q4_2), t)
                    t := mul(a3, and(shr(16, mload(0)), 0xffff))
                    t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                    a3 := sub(add(a1, _Q4_2), t)
                    a1 := add(a1, t)
                    t := mul(u1, and(shr(32, mload(0)), 0xffff))
                    t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                    u1 := sub(add(b1, _Q4_2), t)
                    b1 := add(b1, t)
                    t := mul(a1, and(shr(48, mload(0)), 0xffff))
                    t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                    mstore(p, add(c0, t))
                    mstore(add(p, 0x40), sub(add(c0, _Q4_2), t))
                    t := mul(a3, and(shr(64, mload(0)), 0xffff))
                    t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                    mstore(add(p, 0x80), add(c2, t))
                    mstore(add(p, 0xc0), sub(add(c2, _Q4_2), t))
                    t := mul(b1, and(shr(80, mload(0)), 0xffff))
                    t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                    mstore(add(p, 0x100), add(c4, t))
                    mstore(add(p, 0x140), sub(add(c4, _Q4_2), t))
                    t := mul(u1, and(shr(96, mload(0)), 0xffff))
                    t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                    mstore(add(p, 0x180), add(c6, t))
                    mstore(add(p, 0x1c0), sub(add(c6, _Q4_2), t))
                }
                p := add(p, 32)
            }
        }
    }
}

/// @dev Forward pass C: t = 4 on the pair (2j, 2j+1), then t = 2 and t = 1
///      inside each word (SWAR: lanes (0,1) against (2,3) with S2, then lanes
///      0 and 2 against 1 and 3 with Sa, Sb; Barrett, bias 2q per layer).
///      Twiddles: psirev[64 + j] (table words 4..7), psirev[128 + w] (words
///      8..15), psirev[256 + 2w], psirev[257 + 2w] (words 16..31).
function _fwPassC(uint256[] memory A, uint256 tb) pure {
    assembly ("memory-safe") {
        let p := add(A, 32)
        for { let i1 := 0 } lt(i1, 16) { i1 := add(i1, 1) } {
            mstore(
                0,
                or(
                    and(shr(shl(6, and(i1, 3)), mload(add(tb, add(128, shl(5, shr(2, i1)))))), _L64),
                    shl(64, shr(shl(7, and(i1, 1)), mload(add(tb, add(256, shl(5, shr(1, i1)))))))
                )
            )
            let w1 := mload(add(tb, add(512, shl(5, i1))))
            {
                let U := mload(p)
                let V := mul(mload(add(p, 32)), and(mload(0), 0xffff))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                let X := sub(add(U, _Q4_2), V)
                U := add(U, V)
                let lo := 0
                V := mul(shr(128, U), and(shr(64, mload(0)), 0xffff))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(U, _LO2)
                U := or(add(lo, V), shl(128, sub(add(lo, _Q2_01), V)))
                V := and(shr(64, U), _M02)
                V := or(and(mul(V, and(w1, 0xffff)), _L64), and(mul(V, and(shr(16, w1), 0xffff)), _L2))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(U, _M02)
                U := or(add(lo, V), shl(64, sub(add(lo, _Q2_02), V)))
                mstore(p, U)
                V := mul(shr(128, X), and(shr(80, mload(0)), 0xffff))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(X, _LO2)
                X := or(add(lo, V), shl(128, sub(add(lo, _Q2_01), V)))
                V := and(shr(64, X), _M02)
                V := or(and(mul(V, and(shr(32, w1), 0xffff)), _L64), and(mul(V, and(shr(48, w1), 0xffff)), _L2))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(X, _M02)
                X := or(add(lo, V), shl(64, sub(add(lo, _Q2_02), V)))
                mstore(add(p, 32), X)
            }
            p := add(p, 64)
            {
                let U := mload(p)
                let V := mul(mload(add(p, 32)), and(shr(16, mload(0)), 0xffff))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                let X := sub(add(U, _Q4_2), V)
                U := add(U, V)
                let lo := 0
                V := mul(shr(128, U), and(shr(96, mload(0)), 0xffff))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(U, _LO2)
                U := or(add(lo, V), shl(128, sub(add(lo, _Q2_01), V)))
                V := and(shr(64, U), _M02)
                V := or(and(mul(V, and(shr(64, w1), 0xffff)), _L64), and(mul(V, and(shr(80, w1), 0xffff)), _L2))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(U, _M02)
                U := or(add(lo, V), shl(64, sub(add(lo, _Q2_02), V)))
                mstore(p, U)
                V := mul(shr(128, X), and(shr(112, mload(0)), 0xffff))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(X, _LO2)
                X := or(add(lo, V), shl(128, sub(add(lo, _Q2_01), V)))
                V := and(shr(64, X), _M02)
                V := or(and(mul(V, and(shr(96, w1), 0xffff)), _L64), and(mul(V, and(shr(112, w1), 0xffff)), _L2))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(X, _M02)
                X := or(add(lo, V), shl(64, sub(add(lo, _Q2_02), V)))
                mstore(add(p, 32), X)
            }
            p := add(p, 64)
            {
                let U := mload(p)
                let V := mul(mload(add(p, 32)), and(shr(32, mload(0)), 0xffff))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                let X := sub(add(U, _Q4_2), V)
                U := add(U, V)
                let lo := 0
                V := mul(shr(128, U), and(shr(128, mload(0)), 0xffff))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(U, _LO2)
                U := or(add(lo, V), shl(128, sub(add(lo, _Q2_01), V)))
                V := and(shr(64, U), _M02)
                V := or(and(mul(V, and(shr(128, w1), 0xffff)), _L64), and(mul(V, and(shr(144, w1), 0xffff)), _L2))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(U, _M02)
                U := or(add(lo, V), shl(64, sub(add(lo, _Q2_02), V)))
                mstore(p, U)
                V := mul(shr(128, X), and(shr(144, mload(0)), 0xffff))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(X, _LO2)
                X := or(add(lo, V), shl(128, sub(add(lo, _Q2_01), V)))
                V := and(shr(64, X), _M02)
                V := or(and(mul(V, and(shr(160, w1), 0xffff)), _L64), and(mul(V, and(shr(176, w1), 0xffff)), _L2))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(X, _M02)
                X := or(add(lo, V), shl(64, sub(add(lo, _Q2_02), V)))
                mstore(add(p, 32), X)
            }
            p := add(p, 64)
            {
                let U := mload(p)
                let V := mul(mload(add(p, 32)), and(shr(48, mload(0)), 0xffff))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                let X := sub(add(U, _Q4_2), V)
                U := add(U, V)
                let lo := 0
                V := mul(shr(128, U), and(shr(160, mload(0)), 0xffff))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(U, _LO2)
                U := or(add(lo, V), shl(128, sub(add(lo, _Q2_01), V)))
                V := and(shr(64, U), _M02)
                V := or(and(mul(V, and(shr(192, w1), 0xffff)), _L64), and(mul(V, and(shr(208, w1), 0xffff)), _L2))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(U, _M02)
                U := or(add(lo, V), shl(64, sub(add(lo, _Q2_02), V)))
                mstore(p, U)
                V := mul(shr(128, X), and(shr(176, mload(0)), 0xffff))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(X, _LO2)
                X := or(add(lo, V), shl(128, sub(add(lo, _Q2_01), V)))
                V := and(shr(64, X), _M02)
                V := or(and(mul(V, and(shr(224, w1), 0xffff)), _L64), and(mul(V, and(shr(240, w1), 0xffff)), _L2))
                V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                lo := and(X, _M02)
                X := or(add(lo, V), shl(64, sub(add(lo, _Q2_02), V)))
                mstore(add(p, 32), X)
            }
            p := add(p, 64)
        }
    }
}

/// @notice Forward NTT of a compact polynomial (32 words x 16 coefficients of
///         16 bits, every coefficient < q). Returns 128 packed words with LAZY
///         lanes (< 19q), congruent lane-wise to _nttFwPacked(_packFromCompact(c)).
function _nttFwFused(uint256[] memory c) pure returns (uint256[] memory A) {
    A = _fwPassA(c);
    uint256 tb = _fwTableFused();
    _fwPassB(A, tb);
    _fwPassC(A, tb);
}

/// @dev Inverse pass C': per word, lanes to scalars, pointwise product with
///      the public key (mulmod, exact), t = 1 and t = 2 in-word, then t = 4
///      on the pair (2j, 2j+1). Output lanes < 2q. Pair j reads the 64-bit
///      chunk (j & 1) of compact pk word j >> 1 (eight coefficients).
function _invPassC(uint256[] memory A, uint256[] memory pk, uint256 tb) pure {
    assembly ("memory-safe") {
        let p := add(A, 32)
        for { let i1 := 0 } lt(i1, 16) { i1 := add(i1, 1) } {
            mstore(
                0,
                or(
                    and(shr(shl(6, and(i1, 3)), mload(add(tb, add(128, shl(5, shr(2, i1)))))), _L64),
                    shl(64, shr(shl(7, and(i1, 1)), mload(add(tb, add(256, shl(5, shr(1, i1)))))))
                )
            )
            let w1 := mload(add(tb, add(512, shl(5, i1))))
            {
                let c := mload(add(pk, add(32, shl(6, i1))))
                {
                    let W := mload(p)
                    let l0 := mulmod(and(W, _L64), and(c, 0xffff), 12289)
                    let l1 := mulmod(and(shr(64, W), _L64), and(shr(16, c), 0xffff), 12289)
                    let l2 := mulmod(and(shr(128, W), _L64), and(shr(32, c), 0xffff), 12289)
                    let l3 := mulmod(shr(192, W), and(shr(48, c), 0xffff), 12289)
                    // t = 1: s = a + b (< 2q), d = (a + q - b) S = (s + q - 2b) S
                    l0 := add(l0, l1)
                    l1 := mulmod(sub(add(l0, 12289), shl(1, l1)), and(w1, 0xffff), 12289)
                    l2 := add(l2, l3)
                    l3 := mulmod(sub(add(l2, 12289), shl(1, l3)), and(shr(16, w1), 0xffff), 12289)
                    // t = 2: (s0, d0) against (s1, d1)
                    W := and(shr(64, mload(0)), 0xffff)
                    l3 := or(shl(64, addmod(l1, l3, 12289)), shl(192, mulmod(sub(add(l1, 12289), l3), W, 12289)))
                    l1 := or(mod(add(l0, l2), 12289), shl(128, mulmod(sub(add(l0, 24578), l2), W, 12289)))
                    mstore(p, or(l1, l3))
                }
                {
                    let W := mload(add(p, 32))
                    let l0 := mulmod(and(W, _L64), and(shr(64, c), 0xffff), 12289)
                    let l1 := mulmod(and(shr(64, W), _L64), and(shr(16, shr(64, c)), 0xffff), 12289)
                    let l2 := mulmod(and(shr(128, W), _L64), and(shr(32, shr(64, c)), 0xffff), 12289)
                    let l3 := mulmod(shr(192, W), and(shr(48, shr(64, c)), 0xffff), 12289)
                    // t = 1: s = a + b (< 2q), d = (a + q - b) S = (s + q - 2b) S
                    l0 := add(l0, l1)
                    l1 := mulmod(sub(add(l0, 12289), shl(1, l1)), and(shr(32, w1), 0xffff), 12289)
                    l2 := add(l2, l3)
                    l3 := mulmod(sub(add(l2, 12289), shl(1, l3)), and(shr(48, w1), 0xffff), 12289)
                    // t = 2: (s0, d0) against (s1, d1)
                    W := and(shr(80, mload(0)), 0xffff)
                    l3 := or(shl(64, addmod(l1, l3, 12289)), shl(192, mulmod(sub(add(l1, 12289), l3), W, 12289)))
                    l1 := or(mod(add(l0, l2), 12289), shl(128, mulmod(sub(add(l0, 24578), l2), W, 12289)))
                    mstore(add(p, 32), or(l1, l3))
                }
                {
                    // t = 4 (GS): (U, V) -> (U + V, red((U + q - V) * S)), lanes < 2q
                    let U := mload(p)
                    let V := mload(add(p, 32))
                    mstore(p, add(U, V))
                    V := mul(sub(add(U, _Q4_1), V), and(mload(0), 0xffff))
                    V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                    mstore(add(p, 32), V)
                }
            }
            p := add(p, 64)
            {
                let c := shr(128, mload(add(pk, add(32, shl(6, i1)))))
                {
                    let W := mload(p)
                    let l0 := mulmod(and(W, _L64), and(c, 0xffff), 12289)
                    let l1 := mulmod(and(shr(64, W), _L64), and(shr(16, c), 0xffff), 12289)
                    let l2 := mulmod(and(shr(128, W), _L64), and(shr(32, c), 0xffff), 12289)
                    let l3 := mulmod(shr(192, W), and(shr(48, c), 0xffff), 12289)
                    // t = 1: s = a + b (< 2q), d = (a + q - b) S = (s + q - 2b) S
                    l0 := add(l0, l1)
                    l1 := mulmod(sub(add(l0, 12289), shl(1, l1)), and(shr(64, w1), 0xffff), 12289)
                    l2 := add(l2, l3)
                    l3 := mulmod(sub(add(l2, 12289), shl(1, l3)), and(shr(80, w1), 0xffff), 12289)
                    // t = 2: (s0, d0) against (s1, d1)
                    W := and(shr(96, mload(0)), 0xffff)
                    l3 := or(shl(64, addmod(l1, l3, 12289)), shl(192, mulmod(sub(add(l1, 12289), l3), W, 12289)))
                    l1 := or(mod(add(l0, l2), 12289), shl(128, mulmod(sub(add(l0, 24578), l2), W, 12289)))
                    mstore(p, or(l1, l3))
                }
                {
                    let W := mload(add(p, 32))
                    let l0 := mulmod(and(W, _L64), and(shr(64, c), 0xffff), 12289)
                    let l1 := mulmod(and(shr(64, W), _L64), and(shr(16, shr(64, c)), 0xffff), 12289)
                    let l2 := mulmod(and(shr(128, W), _L64), and(shr(32, shr(64, c)), 0xffff), 12289)
                    let l3 := mulmod(shr(192, W), and(shr(48, shr(64, c)), 0xffff), 12289)
                    // t = 1: s = a + b (< 2q), d = (a + q - b) S = (s + q - 2b) S
                    l0 := add(l0, l1)
                    l1 := mulmod(sub(add(l0, 12289), shl(1, l1)), and(shr(96, w1), 0xffff), 12289)
                    l2 := add(l2, l3)
                    l3 := mulmod(sub(add(l2, 12289), shl(1, l3)), and(shr(112, w1), 0xffff), 12289)
                    // t = 2: (s0, d0) against (s1, d1)
                    W := and(shr(112, mload(0)), 0xffff)
                    l3 := or(shl(64, addmod(l1, l3, 12289)), shl(192, mulmod(sub(add(l1, 12289), l3), W, 12289)))
                    l1 := or(mod(add(l0, l2), 12289), shl(128, mulmod(sub(add(l0, 24578), l2), W, 12289)))
                    mstore(add(p, 32), or(l1, l3))
                }
                {
                    // t = 4 (GS): (U, V) -> (U + V, red((U + q - V) * S)), lanes < 2q
                    let U := mload(p)
                    let V := mload(add(p, 32))
                    mstore(p, add(U, V))
                    V := mul(sub(add(U, _Q4_1), V), and(shr(16, mload(0)), 0xffff))
                    V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                    mstore(add(p, 32), V)
                }
            }
            p := add(p, 64)
            {
                let c := mload(add(pk, add(64, shl(6, i1))))
                {
                    let W := mload(p)
                    let l0 := mulmod(and(W, _L64), and(c, 0xffff), 12289)
                    let l1 := mulmod(and(shr(64, W), _L64), and(shr(16, c), 0xffff), 12289)
                    let l2 := mulmod(and(shr(128, W), _L64), and(shr(32, c), 0xffff), 12289)
                    let l3 := mulmod(shr(192, W), and(shr(48, c), 0xffff), 12289)
                    // t = 1: s = a + b (< 2q), d = (a + q - b) S = (s + q - 2b) S
                    l0 := add(l0, l1)
                    l1 := mulmod(sub(add(l0, 12289), shl(1, l1)), and(shr(128, w1), 0xffff), 12289)
                    l2 := add(l2, l3)
                    l3 := mulmod(sub(add(l2, 12289), shl(1, l3)), and(shr(144, w1), 0xffff), 12289)
                    // t = 2: (s0, d0) against (s1, d1)
                    W := and(shr(128, mload(0)), 0xffff)
                    l3 := or(shl(64, addmod(l1, l3, 12289)), shl(192, mulmod(sub(add(l1, 12289), l3), W, 12289)))
                    l1 := or(mod(add(l0, l2), 12289), shl(128, mulmod(sub(add(l0, 24578), l2), W, 12289)))
                    mstore(p, or(l1, l3))
                }
                {
                    let W := mload(add(p, 32))
                    let l0 := mulmod(and(W, _L64), and(shr(64, c), 0xffff), 12289)
                    let l1 := mulmod(and(shr(64, W), _L64), and(shr(16, shr(64, c)), 0xffff), 12289)
                    let l2 := mulmod(and(shr(128, W), _L64), and(shr(32, shr(64, c)), 0xffff), 12289)
                    let l3 := mulmod(shr(192, W), and(shr(48, shr(64, c)), 0xffff), 12289)
                    // t = 1: s = a + b (< 2q), d = (a + q - b) S = (s + q - 2b) S
                    l0 := add(l0, l1)
                    l1 := mulmod(sub(add(l0, 12289), shl(1, l1)), and(shr(160, w1), 0xffff), 12289)
                    l2 := add(l2, l3)
                    l3 := mulmod(sub(add(l2, 12289), shl(1, l3)), and(shr(176, w1), 0xffff), 12289)
                    // t = 2: (s0, d0) against (s1, d1)
                    W := and(shr(144, mload(0)), 0xffff)
                    l3 := or(shl(64, addmod(l1, l3, 12289)), shl(192, mulmod(sub(add(l1, 12289), l3), W, 12289)))
                    l1 := or(mod(add(l0, l2), 12289), shl(128, mulmod(sub(add(l0, 24578), l2), W, 12289)))
                    mstore(add(p, 32), or(l1, l3))
                }
                {
                    // t = 4 (GS): (U, V) -> (U + V, red((U + q - V) * S)), lanes < 2q
                    let U := mload(p)
                    let V := mload(add(p, 32))
                    mstore(p, add(U, V))
                    V := mul(sub(add(U, _Q4_1), V), and(shr(32, mload(0)), 0xffff))
                    V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                    mstore(add(p, 32), V)
                }
            }
            p := add(p, 64)
            {
                let c := shr(128, mload(add(pk, add(64, shl(6, i1)))))
                {
                    let W := mload(p)
                    let l0 := mulmod(and(W, _L64), and(c, 0xffff), 12289)
                    let l1 := mulmod(and(shr(64, W), _L64), and(shr(16, c), 0xffff), 12289)
                    let l2 := mulmod(and(shr(128, W), _L64), and(shr(32, c), 0xffff), 12289)
                    let l3 := mulmod(shr(192, W), and(shr(48, c), 0xffff), 12289)
                    // t = 1: s = a + b (< 2q), d = (a + q - b) S = (s + q - 2b) S
                    l0 := add(l0, l1)
                    l1 := mulmod(sub(add(l0, 12289), shl(1, l1)), and(shr(192, w1), 0xffff), 12289)
                    l2 := add(l2, l3)
                    l3 := mulmod(sub(add(l2, 12289), shl(1, l3)), and(shr(208, w1), 0xffff), 12289)
                    // t = 2: (s0, d0) against (s1, d1)
                    W := and(shr(160, mload(0)), 0xffff)
                    l3 := or(shl(64, addmod(l1, l3, 12289)), shl(192, mulmod(sub(add(l1, 12289), l3), W, 12289)))
                    l1 := or(mod(add(l0, l2), 12289), shl(128, mulmod(sub(add(l0, 24578), l2), W, 12289)))
                    mstore(p, or(l1, l3))
                }
                {
                    let W := mload(add(p, 32))
                    let l0 := mulmod(and(W, _L64), and(shr(64, c), 0xffff), 12289)
                    let l1 := mulmod(and(shr(64, W), _L64), and(shr(16, shr(64, c)), 0xffff), 12289)
                    let l2 := mulmod(and(shr(128, W), _L64), and(shr(32, shr(64, c)), 0xffff), 12289)
                    let l3 := mulmod(shr(192, W), and(shr(48, shr(64, c)), 0xffff), 12289)
                    // t = 1: s = a + b (< 2q), d = (a + q - b) S = (s + q - 2b) S
                    l0 := add(l0, l1)
                    l1 := mulmod(sub(add(l0, 12289), shl(1, l1)), and(shr(224, w1), 0xffff), 12289)
                    l2 := add(l2, l3)
                    l3 := mulmod(sub(add(l2, 12289), shl(1, l3)), and(shr(240, w1), 0xffff), 12289)
                    // t = 2: (s0, d0) against (s1, d1)
                    W := and(shr(176, mload(0)), 0xffff)
                    l3 := or(shl(64, addmod(l1, l3, 12289)), shl(192, mulmod(sub(add(l1, 12289), l3), W, 12289)))
                    l1 := or(mod(add(l0, l2), 12289), shl(128, mulmod(sub(add(l0, 24578), l2), W, 12289)))
                    mstore(add(p, 32), or(l1, l3))
                }
                {
                    // t = 4 (GS): (U, V) -> (U + V, red((U + q - V) * S)), lanes < 2q
                    let U := mload(p)
                    let V := mload(add(p, 32))
                    mstore(p, add(U, V))
                    V := mul(sub(add(U, _Q4_1), V), and(shr(48, mload(0)), 0xffff))
                    V := sub(V, mul(and(shr(40, mul(V, 89471204)), _QHAT24), 12289))
                    mstore(add(p, 32), V)
                }
            }
            p := add(p, 64)
        }
    }
}

/// @dev Inverse pass B': t = 8, 16, 32 on the octets (16b + r, +2, ..., +14).
///      Sums are never reduced: lanes < 2q in, < 16q out.
function _invPassB(uint256[] memory A, uint256 tb) pure {
    assembly ("memory-safe") {
        for { let b := 0 } lt(b, 8) { b := add(b, 1) } {
            {
                let w := mload(add(tb, add(64, shl(5, shr(2, b)))))
                mstore(
                    0,
                    or(
                        or(
                            and(shr(shl(4, add(8, b)), mload(tb)), 0xffff),
                            shl(16, and(shr(shl(5, b), mload(add(tb, 32))), 0xffffffff))
                        ),
                        shl(48, and(shr(shl(6, and(b, 3)), w), _L64))
                    )
                )
            }
            let p := add(add(A, 32), shl(9, b))
            for { let r := 0 } lt(r, 2) { r := add(r, 1) } {
                let b0, b1, b2, b3
                {
                    let u := mload(p)
                    let v := mload(add(p, 0x40))
                    let t := mul(sub(add(u, _Q4_2), v), and(shr(48, mload(0)), 0xffff))
                    t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                    u := add(u, v)
                    v := mload(add(p, 0x80))
                    let w := mload(add(p, 0xc0))
                    let s := mul(sub(add(v, _Q4_2), w), and(shr(64, mload(0)), 0xffff))
                    s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                    v := add(v, w)
                    w := mul(sub(add(u, _Q4_4), v), and(shr(16, mload(0)), 0xffff))
                    w := sub(w, mul(and(shr(40, mul(w, 89471204)), _QHAT24), 12289))
                    b0 := add(u, v)
                    b2 := w
                    w := mul(sub(add(t, _Q4_4), s), and(shr(16, mload(0)), 0xffff))
                    w := sub(w, mul(and(shr(40, mul(w, 89471204)), _QHAT24), 12289))
                    b1 := add(t, s)
                    b3 := w
                }
                {
                    let u := mload(add(p, 0x100))
                    let v := mload(add(p, 0x140))
                    let t := mul(sub(add(u, _Q4_2), v), and(shr(80, mload(0)), 0xffff))
                    t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                    u := add(u, v)
                    v := mload(add(p, 0x180))
                    let w := mload(add(p, 0x1c0))
                    let s := mul(sub(add(v, _Q4_2), w), and(shr(96, mload(0)), 0xffff))
                    s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                    v := add(v, w)
                    w := mul(sub(add(u, _Q4_4), v), and(shr(32, mload(0)), 0xffff))
                    w := sub(w, mul(and(shr(40, mul(w, 89471204)), _QHAT24), 12289))
                    u := add(u, v)
                    v := mul(sub(add(t, _Q4_4), s), and(shr(32, mload(0)), 0xffff))
                    v := sub(v, mul(and(shr(40, mul(v, 89471204)), _QHAT24), 12289))
                    t := add(t, s)
                    s := mul(sub(add(b0, _Q4_8), u), and(mload(0), 0xffff))
                    s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                    mstore(add(p, 0x100), s)
                    mstore(p, add(b0, u))
                    s := mul(sub(add(b1, _Q4_8), t), and(mload(0), 0xffff))
                    s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                    mstore(add(p, 0x140), s)
                    mstore(add(p, 0x40), add(b1, t))
                    s := mul(sub(add(b2, _Q4_8), w), and(mload(0), 0xffff))
                    s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                    mstore(add(p, 0x180), s)
                    mstore(add(p, 0x80), add(b2, w))
                    s := mul(sub(add(b3, _Q4_8), v), and(mload(0), 0xffff))
                    s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                    mstore(add(p, 0x1c0), s)
                    mstore(add(p, 0xc0), add(b3, v))
                }
                p := add(p, 32)
            }
        }
    }
}

/// @dev Inverse pass A': t = 64, 128, 256 on the octet (i, i+16, ..., i+112)
///      with n^-1 folded into the last layer (psirev[1] * n^-1 is a literal);
///      every output lane canonical (< q).
function _invPassA(uint256[] memory A) pure {
    assembly ("memory-safe") {
        for { let i := 0 } lt(i, 16) { i := add(i, 1) } {
            let p := add(add(A, 32), shl(5, i))
            let b0, b1, b2, b3
            {
                let u := mload(p)
                let v := mload(add(p, 0x200))
                let t := mul(sub(add(u, _Q4_16), v), 0x1026)
                t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                u := add(u, v)
                v := mload(add(p, 0x400))
                let w := mload(add(p, 0x600))
                let s := mul(sub(add(v, _Q4_16), w), 0x1999)
                s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                v := add(v, w)
                w := mul(sub(add(u, _Q4_32), v), 0x2036)
                w := sub(w, mul(and(shr(40, mul(w, 89471204)), _QHAT24), 12289))
                b0 := add(u, v)
                b2 := w
                w := mul(sub(add(t, _Q4_32), s), 0x2036)
                w := sub(w, mul(and(shr(40, mul(w, 89471204)), _QHAT24), 12289))
                b1 := add(t, s)
                b3 := w
            }
            {
                let u := mload(add(p, 0x800))
                let v := mload(add(p, 0xa00))
                let t := mul(sub(add(u, _Q4_16), v), 0x2d2f)
                t := sub(t, mul(and(shr(40, mul(t, 89471204)), _QHAT24), 12289))
                u := add(u, v)
                v := mload(add(p, 0xc00))
                let w := mload(add(p, 0xe00))
                let s := mul(sub(add(v, _Q4_16), w), 0x519)
                s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                v := add(v, w)
                w := mul(sub(add(u, _Q4_32), v), 0x141a)
                w := sub(w, mul(and(shr(40, mul(w, 89471204)), _QHAT24), 12289))
                u := add(u, v)
                v := mul(sub(add(t, _Q4_32), s), 0x141a)
                v := sub(v, mul(and(shr(40, mul(v, 89471204)), _QHAT24), 12289))
                t := add(t, s)
                s := mul(sub(add(b0, _Q4_64), u), 0x55b)
                s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                s := sub(s, mul(shr(14, and(add(s, _C14), _H14)), 12289))
                mstore(add(p, 0x800), s)
                s := mul(add(b0, u), 12265)
                s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                s := sub(s, mul(shr(14, and(add(s, _C14), _H14)), 12289))
                mstore(p, s)
                s := mul(sub(add(b1, _Q4_64), t), 0x55b)
                s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                s := sub(s, mul(shr(14, and(add(s, _C14), _H14)), 12289))
                mstore(add(p, 0xa00), s)
                s := mul(add(b1, t), 12265)
                s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                s := sub(s, mul(shr(14, and(add(s, _C14), _H14)), 12289))
                mstore(add(p, 0x200), s)
                s := mul(sub(add(b2, _Q4_64), w), 0x55b)
                s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                s := sub(s, mul(shr(14, and(add(s, _C14), _H14)), 12289))
                mstore(add(p, 0xc00), s)
                s := mul(add(b2, w), 12265)
                s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                s := sub(s, mul(shr(14, and(add(s, _C14), _H14)), 12289))
                mstore(add(p, 0x400), s)
                s := mul(sub(add(b3, _Q4_64), v), 0x55b)
                s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                s := sub(s, mul(shr(14, and(add(s, _C14), _H14)), 12289))
                mstore(add(p, 0xe00), s)
                s := mul(add(b3, v), 12265)
                s := sub(s, mul(and(shr(40, mul(s, 89471204)), _QHAT24), 12289))
                s := sub(s, mul(shr(14, and(add(s, _C14), _H14)), 12289))
                mstore(add(p, 0x600), s)
            }
        }
    }
}

/// @notice Pointwise product with the compact public key (32 words x 16
///         coefficients of 16 bits, every coefficient < q) followed by the
///         inverse NTT, in place on the 128 packed words A. Input lanes may be
///         lazy (any value < 2^64). Output lanes are CANONICAL (< q) and equal,
///         lane-wise, to _nttInvPacked(_vecMulPacked(A, _packFromCompact(pk)))
///         reduced mod q.
function _nttInvFusedMul(uint256[] memory A, uint256[] memory pk) pure returns (uint256[] memory) {
    uint256 tb = _invTableFused();
    _invPassC(A, pk, tb);
    _invPassB(A, tb);
    _invPassA(A);
    return A;
}

uint256 constant _Q16 = 0x3001300130013001300130013001300130013001300130013001300130013001;
uint256 constant _CAN16 = 0x4fff4fff4fff4fff4fff4fff4fff4fff4fff4fff4fff4fff4fff4fff4fff4fff;
uint256 constant _CEN16 = 0x67ff67ff67ff67ff67ff67ff67ff67ff67ff67ff67ff67ff67ff67ff67ff67ff;
uint256 constant _H16 = 0x8000800080008000800080008000800080008000800080008000800080008000;
uint256 constant _M64LO = 0x0000000000000000ffffffffffffffff0000000000000000ffffffffffffffff;
uint256 constant _M64HI = 0xffffffffffffffff0000000000000000ffffffffffffffff0000000000000000;
uint256 constant _M32LO = 0x00000000ffffffff00000000ffffffff00000000ffffffff00000000ffffffff;
uint256 constant _M32HI = 0xffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000;
uint256 constant _M16LO = 0x0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff;
uint256 constant _M16HI = 0xffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000;

/// @notice Range check and centred squared norm of a compact polynomial (32
///         words x 16 coefficients of 16 bits). outOfRange != 0 iff some
///         coefficient is >= q; norm = sum of min(v, q - v)^2, as in
///         falcon_normalize (meaningful only when outOfRange == 0).
function _s2NormCompact(uint256[] memory c) pure returns (uint256 outOfRange, uint256 norm) {
    assembly ("memory-safe") {
        let p := add(c, 32)
        let pe := add(p, 1024)
        for {} lt(p, pe) { p := add(p, 32) } {
            let v := mload(p)
            // v >= q  <=>  bit 15 or bit 14 of v, or bit 14 of ((v & 0x3fff) + 2^14 - q)
            outOfRange := or(outOfRange, and(v, 0xc000c000c000c000c000c000c000c000c000c000c000c000c000c000c000c000))
            outOfRange := or(
                outOfRange,
                and(
                    add(
                        and(v, 0x3fff3fff3fff3fff3fff3fff3fff3fff3fff3fff3fff3fff3fff3fff3fff3fff),
                        0x0fff0fff0fff0fff0fff0fff0fff0fff0fff0fff0fff0fff0fff0fff0fff0fff
                    ),
                    0x4000400040004000400040004000400040004000400040004000400040004000
                )
            )
            let f := 0
            // centre: fields with v > q/2 take q - v
            f := and(add(v, _CEN16), _H16)
            f := or(f, sub(f, shr(15, f)))
            v := xor(v, and(f, xor(v, sub(_Q16, v))))
            // reverse the sixteen fields
            f := or(shl(128, v), shr(128, v))
            f := or(shl(64, and(f, _M64LO)), shr(64, and(f, _M64HI)))
            f := or(shl(32, and(f, _M32LO)), shr(32, and(f, _M32HI)))
            f := or(shl(16, and(f, _M16LO)), shr(16, and(f, _M16HI)))
            // even fields against reversed even fields, odd against reversed odd
            norm := add(norm, shr(224, mul(and(v, _M16LO), and(shr(16, f), _M16LO))))
            norm := add(norm, shr(224, mul(and(shr(16, v), _M16LO), and(f, _M16LO))))
        }
    }
}

/// @notice Centred squared norm of h - s (mod q) over 512 coefficients given
///         as 128 packed words each (4 canonical 64-bit lanes per word), i.e.
///         the ||s1||^2 half of falcon_normalize with s1 = h - s.
function _normS1Packed(uint256[] memory h, uint256[] memory s) pure returns (uint256 norm) {
    assembly ("memory-safe") {
        let ph := add(h, 32)
        let ps := add(s, 32)
        let pe := add(ph, 4096)
        for {} lt(ph, pe) {
            ph := add(ph, 128)
            ps := add(ps, 128)
        } {
            // four words of lanes h + q - s (< 2q < 2^15) interleaved into one
            // word of sixteen 16-bit fields (the order does not matter here)
            let v := sub(add(mload(ph), _Q4_1), mload(ps))
            v := or(v, shl(16, sub(add(mload(add(ph, 32)), _Q4_1), mload(add(ps, 32)))))
            v := or(v, shl(32, sub(add(mload(add(ph, 64)), _Q4_1), mload(add(ps, 64)))))
            v := or(v, shl(48, sub(add(mload(add(ph, 96)), _Q4_1), mload(add(ps, 96)))))
            // canonicalise: fields >= q lose q
            let f := and(add(v, _CAN16), _H16)
            v := sub(v, mul(shr(15, f), 12289))
            // centre: fields with v > q/2 take q - v
            f := and(add(v, _CEN16), _H16)
            f := or(f, sub(f, shr(15, f)))
            v := xor(v, and(f, xor(v, sub(_Q16, v))))
            // reverse the sixteen fields
            f := or(shl(128, v), shr(128, v))
            f := or(shl(64, and(f, _M64LO)), shr(64, and(f, _M64HI)))
            f := or(shl(32, and(f, _M32LO)), shr(32, and(f, _M32HI)))
            f := or(shl(16, and(f, _M16LO)), shr(16, and(f, _M16HI)))
            // even fields against reversed even fields, odd against reversed odd
            norm := add(norm, shr(224, mul(and(v, _M16LO), and(shr(16, f), _M16LO))))
            norm := add(norm, shr(224, mul(and(shr(16, v), _M16LO), and(f, _M16LO))))
        }
    }
}
