// SPDX-License-Identifier: MIT
// Copyright (C) 2026 - ZKNOX
// License: This software is licensed under MIT License
// This Code may be reused including this header, license and copyright notice.
// FILE: ZKNOX_falcon_core8.sol
// falcon_core on the eight-lane Montgomery chain (ZKNOX_NTT_falcon8.sol) with
// the ||h - s1||^2 half of the norm folded into hash-to-point: the product
// s1 = INTT(NTT(s2) o h) is computed first, its lanes stored as
// c_i = 3q + 6144 - s1_i, then the sampler accumulates ((t + c_i) mod q -
// 6144)^2 for each accepted candidate t and never stores h. For a canonical difference v = (h - s1) mod q this is v^2
// when v <= 6144 and (q - v)^2 otherwise, i.e. the centred square of
// falcon_normalize. s1 lanes are < 3q and t < 5q, so the mod argument is
// positive; the square of a value in [-6144, 6144] taken in two's complement
// is exact. Candidates are tested four at a time: for a 16-bit t,
// ((t & 0x7fff) + 0x0ffb) & t & 0x8000 is nonzero iff t >= 5q = 61445, and
// the same masks work on the four candidates of a state lane at once; when
// all four pass (and, in the last blocks, four output slots remain) they are
// consumed with one branch: the four candidates spread to 32-bit spacing are
// added to the four complement lanes of s1 in one add, each sum then reduced,
// centred and squared. A block whose starting count is <= 444 cannot overflow 512 within
// its 68 candidates, so it runs without output-bound checks.
// The helper is our own Keccak-f[1600] (pythonref/gen_keccak_helper.py, see
// below); the SHAKE padding and lane conventions are those of the Fireblocks
// glue (MIT) that the other verifiers still use.
pragma solidity ^0.8.25;

import "./ZKNOX_falcon_utils.sol";
import "./ZKNOX_shake_fast.sol";
import {falconProduct8} from "./ZKNOX_NTT_falcon8.sol";
import {_s2NormCompact} from "./ZKNOX_NTT_falcon_fused.sol";

// ---- resident replicated SHAKE lanes ---------------------------------------
// The helper's permutation works on words holding four copies of each 64-bit
// lane (rotations then need no mask); its clean-lane interface replicates on
// entry and masks on exit. Its resident interface (test/f1600_zknox.hex,
// generated by pythonref/gen_keccak_helper.py) takes the 25 replicated words
// (plus one ignored byte, 801 bytes in all)
// followed by 25 replicated words and returns 25 replicated words, so the
// caller keeps the replicated form: absorption XORs replicated message lanes
// into a zero state, the sampler reads the low copy (its byte-swap masks are
// 64-bit wide and drop the other three).

uint256 constant _REP4 = 0x0000000000000001000000000000000100000000000000010000000000000001;

/// @dev permutation on the replicated state (801-byte interface: the 25
///      words, plus one byte the helper ignores)
function _f1600Resident(uint256 st, address helper) view {
    bool ok;
    assembly ("memory-safe") {
        ok := staticcall(gas(), helper, st, 801, st, 800)
        ok := and(ok, eq(returndatasize(), 800))
    }
    if (!ok) revert HelperCallFailed();
}

/// @dev absorb one 136-byte rate block at `ptr` (bytes, little-endian lanes)
///      into the replicated state at `st`
function _xorBlockResident(uint256 st, uint256 ptr) pure {
    assembly ("memory-safe") {
        function grev(w) -> v {
            let a := and(w, 0xff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00)
            v := or(shr(8, a), shl(8, xor(w, a)))
            a := and(v, 0xffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000)
            v := or(shr(16, a), shl(16, xor(v, a)))
            a := and(v, 0xffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000)
            v := or(shr(32, a), shl(32, xor(v, a)))
        }
        for { let i := 0 } lt(i, 17) { i := add(i, 1) } {
            // lane i = bytes 8i .. 8i+7, little-endian: the reversed word's field
            let v := shr(192, grev(mload(add(ptr, shl(3, i)))))
            let p := add(st, shl(5, i))
            mstore(p, xor(mload(p), mul(v, _REP4)))
        }
    }
}

/// @dev SHAKE256 absorption of `input` (padding 0x1f / 0x80) into the zero
///      replicated state at `st`
function _absorbResident(uint256 st, bytes memory input, address helper) view {
    uint256 ptr;
    uint256 len = input.length;
    assembly ("memory-safe") {
        ptr := add(input, 32)
    }
    unchecked {
        uint256 nFull = len / 136;
        for (uint256 i = 0; i < nFull; ++i) {
            _xorBlockResident(st, ptr);
            _f1600Resident(st, helper);
            ptr += 136;
        }
        uint256 rem = len - nFull * 136;
        bytes memory last = new bytes(136);
        assembly ("memory-safe") {
            let dst := add(last, 32)
            mcopy(dst, ptr, rem)
            mstore8(add(dst, rem), 0x1f)
            mstore(add(dst, 104), xor(mload(add(dst, 104)), 0x80))
            ptr := dst
        }
        _xorBlockResident(st, ptr);
        _f1600Resident(st, helper);
    }
}

error HelperCallFailed();

/// @notice hashToPointNIST(salt, msgHash) consumed on the fly: returns
///         sum over i of centred(h_i - s1_i)^2, with s1 packed on eight lanes
///         as 3q + 6144 - s1_i (falconProduct8).
function hashToPointNormS1(bytes memory salt, bytes memory msgHash, address helper, uint256[] memory s1)
    view
    returns (uint256 norm)
{
    require(s1.length == 64, "s1 length");
    // replicated state
    uint256[25] memory buf;
    uint256 st;
    assembly ("memory-safe") {
        st := buf
    }
    _absorbResident(st, abi.encodePacked(salt, msgHash), helper);
    uint256 i;
    uint256 s1p;
    assembly ("memory-safe") {
        s1p := add(s1, 32)
    }
    while (true) {
        assembly ("memory-safe") {
            // A block holds at most 68 candidates: when it starts below 445 outputs
            // it cannot reach 512, so the block runs without output-bound checks.
            switch lt(i, 445)
            case 1 {
                for { let lp := st } lt(lp, add(st, 544)) { lp := add(lp, 32) } {
                    let lane := mload(lp)
                    lane := or(shr(8, and(lane, 0xff00ff00ff00ff00)), shl(8, and(lane, 0x00ff00ff00ff00ff)))
                    switch and(and(add(and(lane, 0x7fff7fff7fff7fff), 0x0ffb0ffb0ffb0ffb), lane), 0x8000800080008000)
                    case 0 {
                        // all four below 5q: the four candidates spread to 32-bit spacing (two
                        // mask/shift steps) are added to the four complement lanes of s1 in one
                        // add, then each sum is reduced, centred and squared
                        let ptr := add(s1p, shl(5, shr(3, i)))
                        let sh := shl(5, and(i, 7))
                        let x := shr(sh, mload(ptr))
                        if gt(sh, 128) { x := or(x, shl(sub(256, sh), mload(add(ptr, 32)))) }
                        let y := or(and(lane, 0xffffffff), shl(32, and(lane, 0xffffffff00000000)))
                        x := add(
                            x,
                            or(
                                and(y, 0x000000000000ffff000000000000ffff),
                                shl(16, and(y, 0x00000000ffff000000000000ffff0000))
                            )
                        )
                        let d := sub(mod(and(x, 0xffffffff), 12289), 6144)
                        norm := add(norm, mul(d, d))
                        d := sub(mod(and(shr(32, x), 0xffffffff), 12289), 6144)
                        norm := add(norm, mul(d, d))
                        d := sub(mod(and(shr(64, x), 0xffffffff), 12289), 6144)
                        norm := add(norm, mul(d, d))
                        d := sub(mod(and(shr(96, x), 0xffffffff), 12289), 6144)
                        norm := add(norm, mul(d, d))
                        i := add(i, 4)
                    }
                    default {
                        for { let k := 0 } lt(k, 4) { k := add(k, 1) } {
                            let v := and(shr(shl(4, k), lane), 0xffff)
                            if lt(v, 61445) {
                                let d :=
                                    sub(
                                        mod(
                                            add(
                                                v,
                                                and(
                                                    shr(shl(5, and(i, 7)), mload(add(s1p, shl(5, shr(3, i))))),
                                                    0xffffffff
                                                )
                                            ),
                                            12289
                                        ),
                                        6144
                                    )
                                norm := add(norm, mul(d, d))
                                i := add(i, 1)
                            }
                        }
                    }
                }
            }
            default {
                for { let lp := st } lt(lp, add(st, 544)) { lp := add(lp, 32) } {
                    let lane := mload(lp)
                    lane := or(shr(8, and(lane, 0xff00ff00ff00ff00)), shl(8, and(lane, 0x00ff00ff00ff00ff)))
                    switch and(
                        iszero(
                            and(and(add(and(lane, 0x7fff7fff7fff7fff), 0x0ffb0ffb0ffb0ffb), lane), 0x8000800080008000)
                        ),
                        lt(i, 509)
                    )
                    case 1 {
                        let ptr := add(s1p, shl(5, shr(3, i)))
                        let sh := shl(5, and(i, 7))
                        let x := shr(sh, mload(ptr))
                        if gt(sh, 128) { x := or(x, shl(sub(256, sh), mload(add(ptr, 32)))) }
                        let y := or(and(lane, 0xffffffff), shl(32, and(lane, 0xffffffff00000000)))
                        x := add(
                            x,
                            or(
                                and(y, 0x000000000000ffff000000000000ffff),
                                shl(16, and(y, 0x00000000ffff000000000000ffff0000))
                            )
                        )
                        let d := sub(mod(and(x, 0xffffffff), 12289), 6144)
                        norm := add(norm, mul(d, d))
                        d := sub(mod(and(shr(32, x), 0xffffffff), 12289), 6144)
                        norm := add(norm, mul(d, d))
                        d := sub(mod(and(shr(64, x), 0xffffffff), 12289), 6144)
                        norm := add(norm, mul(d, d))
                        d := sub(mod(and(shr(96, x), 0xffffffff), 12289), 6144)
                        norm := add(norm, mul(d, d))
                        i := add(i, 4)
                    }
                    default {
                        for { let k := 0 } lt(k, 4) { k := add(k, 1) } {
                            let v := and(shr(shl(4, k), lane), 0xffff)
                            if and(lt(v, 61445), lt(i, 512)) {
                                let d :=
                                    sub(
                                        mod(
                                            add(
                                                v,
                                                and(
                                                    shr(shl(5, and(i, 7)), mload(add(s1p, shl(5, shr(3, i))))),
                                                    0xffffffff
                                                )
                                            ),
                                            12289
                                        ),
                                        6144
                                    )
                                norm := add(norm, mul(d, d))
                                i := add(i, 1)
                            }
                        }
                    }
                    if eq(i, 512) { lp := add(st, 512) }
                }
            }
        }
        if (i == 512) break;
        _f1600Resident(st, helper);
    }
}

/// @notice falcon_core on the eight-lane chain: accepts iff s2 is in range,
///         and ||s2||^2 + ||h - s1||^2 <= sigBound with s1 = INTT(NTT(s2) o h)
///         and h = hashToPointNIST(salt, msgHash).
function falcon_core8(
    bytes memory salt,
    bytes memory msgHash,
    address helper,
    uint256[] memory s2,
    uint256[] memory ntth
) view returns (bool) {
    if (s2.length != 32 || ntth.length != 32) return false;
    (uint256 outOfRange, uint256 norm) = _s2NormCompact(s2);
    if (outOfRange != 0) return false;
    uint256[] memory s1 = falconProduct8(s2, ntth);
    norm += hashToPointNormS1(salt, msgHash, helper, s1);
    return norm <= sigBound;
}
