name: Python Tests

on:
  push:
    branches:
      - main
      - dev  # Add other branches if needed
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Change to your required Python version

      - name: Install make & dependencies
        run: sudo apt-get update && sudo apt-get install -y make curl

      - name: Install Foundry (Manual Method)
        run: |
          mkdir -p $HOME/.foundry/bin
          # Download the correct binary for Linux
          curl -L https://github.com/foundry-rs/foundry/releases/latest/download/foundry-toolchain-linux-x86_64 -o $HOME/.foundry/bin/foundryup
          chmod +x $HOME/.foundry/bin/foundryup
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH
          export PATH="$HOME/.foundry/bin:$PATH"
          foundryup 

      - name: Debug Foundry Installation
        run: |
          echo "PATH: $PATH"
          which foundryup
          foundryup --version

      - name: Install dependencies with Makefile
        run: make install

      - name: Run Tests
        run: |
          source myenv/bin/activate  # Activate the virtual environment
          make test