name: Python Tests

on:
  push:
    branches:
      - main
      - dev  # Add other branches if needed
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Change to your required Python version

      - name: Install make (if not available)
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Install dependencies with Makefile
        run: make install

      - name: Run Tests
        run: |
          source myenv/bin/activate  # Activate the virtual environment
          make test